[versions]
projektor = "4.+"

foojay-resolver-plugin = "1.0.0"
gradle-develocity-plugin = "4.2.2"

shadow-plugin = "9.2.2"
build-config-plugin = "5.7.1"
plugin-publish-plugin = "1.3.1"

parchment-plugin = "1.2.0"
fabric-plugin = "1.11-SNAPSHOT"
legacy-fabric-plugin = "1.11-SNAPSHOT"
ornithe-plugin = "1.11-SNAPSHOT"
forge-plugin = "6.0.46"
neoforge-plugin = "2.0.116"
modrinth-minotaur-plugin = "2.8.10"

kotlin = "2.0.21"
kotlin-serialization-xml = "0.90.1"
ktor = "3.0.0"
kotlin-html = "0.12.0"

kotlin-utils = "0.8.4"
gradle-utils = "0.8.9"
kotlin-shell-dsl = "0.8.2"

java-poet = "0.7.0"
jsoup = "1.21.2"
okio = "3.9.1"

[plugins]
projektor = { id = "io.github.diskria.projektor", version.ref = "projektor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
kotlin-utils = { group = "io.github.diskria", name = "kotlin-utils", version.ref = "kotlin-utils" }
gradle-utils = { group = "io.github.diskria", name = "gradle-utils", version.ref = "gradle-utils" }
kotlin-shell-dsl = { group = "io.github.diskria", name = "kotlin-shell-dsl", version.ref = "kotlin-shell-dsl" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }

kotlin-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html-jvm", version.ref = "kotlin-html" }
kotlin-serialization-xml = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "kotlin-serialization-xml" }

foojay-resolver-plugin = { group = "org.gradle.toolchains.foojay-resolver-convention", name = "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version.ref = "foojay-resolver-plugin" }
gradle-develocity-plugin = { group = "com.gradle.develocity", name = "com.gradle.develocity.gradle.plugin", version.ref = "gradle-develocity-plugin" }

kotlin-jvm-plugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
shadow-plugin = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow-plugin" }
build-config-plugin = { group = "com.github.gmazzo.buildconfig", name = "com.github.gmazzo.buildconfig.gradle.plugin", version.ref = "build-config-plugin" }
plugin-publish-plugin = { group = "com.gradle.publish", name = "plugin-publish-plugin", version.ref = "plugin-publish-plugin" }

parchment-plugin = { group = "org.parchmentmc.librarian.forgegradle", name = "org.parchmentmc.librarian.forgegradle.gradle.plugin", version.ref = "parchment-plugin" }
fabric-plugin = { group = "fabric-loom", name = "fabric-loom.gradle.plugin", version.ref = "fabric-plugin" }
legacy-fabric-plugin = { group = "legacy-looming", name = "legacy-looming.gradle.plugin", version.ref = "legacy-fabric-plugin" }
ornithe-plugin = { group = "ploceus", name = "ploceus.gradle.plugin", version.ref = "ornithe-plugin" }
forge-plugin = { group = "net.minecraftforge.gradle", name = "net.minecraftforge.gradle.gradle.plugin", version.ref = "forge-plugin" }
neoforge-plugin = { group = "net.neoforged.moddev", name = "net.neoforged.moddev.gradle.plugin", version.ref = "neoforge-plugin" }
modrinth-minotaur-plugin = { group = "com.modrinth.minotaur", name = "com.modrinth.minotaur.gradle.plugin", version.ref = "modrinth-minotaur-plugin" }

java-poet = { group = "com.palantir.javapoet", name = "javapoet", version.ref = "java-poet" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
okio = { group = "com.squareup.okio", name = "okio-jvm", version.ref = "okio" }

[bundles]
diskria-utils = [
    "kotlin-utils",
    "gradle-utils",
    "kotlin-shell-dsl",
]
ktor-client = [
    "ktor-client-core",
    "ktor-client-cio",
]
implementation-settings-plugins = [
    "foojay-resolver-plugin",
    "gradle-develocity-plugin",
]
implementation-project-plugins = [
    "kotlin-jvm-plugin",
    "kotlin-serialization-plugin",
    "shadow-plugin",
    "build-config-plugin",
    "plugin-publish-plugin",
    "parchment-plugin",
    "fabric-plugin",
    "legacy-fabric-plugin",
    "ornithe-plugin",
    "forge-plugin",
    "neoforge-plugin",
    "modrinth-minotaur-plugin",
]
